#!/bin/sh

case "$1" in
	--url=* )
		url="${1#--url=}"
		;;
	--url )
		url="$2"
		;;
esac

dbus-send --session --type=method_call --print-reply --dest="com.nokia.osso_browser" /com/nokia/osso_browser/request com.nokia.osso_browser.open_new_window string:${url:-"new_window"} > /dev/null 2>&1
exit 0
