#!/bin/sh

case "$1" in
	--url=* )
		url="${1#--url=}"
		;;
	--url )
		url="$2"
		;;
esac

if pidof browser > /dev/null 2>&1; then
	dest="com.nokia.osso_browser"
	path="/com/nokia/osso_browser/request"
	method="com.nokia.osso_browser.open_new_window"
else
	dest="org.maemo.garage.browser_switchboard"
	path="/org/maemo/garage/browser_switchboard"
	method="org.maemo.garage.browser_switchboard.launch_microb"
fi

dbus-send --session --type=method_call --print-reply --dest="$dest" "$path" "$method" string:${url:-"new_window"} > /dev/null 2>&1
exit 0
